repository: uittorio/cv
favicon: images/favicon.ico

version: 2

name: Vittorio Guerriero
title: Software Engineer
email: vittorio.gue@gmail.com
website: https://uittorio.github.io/

darkmode: true

github_username:  uittorio
linkedin_username: vittorio-guerriero

additional_links:
- title: ts-auto-mock
  icon: fas fa-globe
  url: https://typescript-tdd.github.io/ts-auto-mock/

about_profile_image: images/profile.jpg
about_content: |
  I bring nearly a decade of experience, primarily in web application development, with deep expertise in JavaScript, TypeScript, and C#. 
  I'm passionate about extreme programming principles, believing in reducing the feedback loop to the smallest cycle, from the technical side to the product side. 

content:
  - title: Projects
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Ts auto mock
        link: https://typescript-tdd.github.io/ts-auto-mock/
        additional_links:
          - title: github link
            icon: fab fa-github
            url: https://github.com/Typescript-TDD/ts-auto-mock/
        quote: >
          TypeScript transformer to create mocks from any type
        description: | 
          I've started this project with a friend to find a better alternative to the current mocking ecosystem in Typescript.
          The project has more than <mark>500</mark> stars and <mark>30k</mark> downloads a week.
          This project helped us exploring different ways of testing, how to build functionalities for others and how to collaborate with developers we've never worked with
          
          ---

      - layout: top-middle
        title: Arduino pomodoro timer
        link: https://github.com/uittorio/arduino-timer
        quote: |
          Every developer needs a break! I've created this device to help me focus while working. 
          A short break every 30 minutes.
        description: |
          {:refdef: style="text-align: center; width: 50%; margin: auto;" }
          ![Arduino](images/arduino.jpg "Arduino")
          {: refdef}
          ---

      - layout: top-middle
        title: My wedding website
        link: https://marlenevittorio.github.io/
        quote: This is nothing special, but if you want to get to know me better there is a section with some funny wedding pictures

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Dataglide
        quote: >
          A lot of experiments
        sub_title: Senior Software Engineer
        caption: April 2023 - Present
        description: |
          At Dataglide, I guided the software engineering team in improving their CI/CD, pair programming, and testing practices.
          I advised a ‘push-directly-to-production’ approach, which drove significant improvements in observability, testing practises, and team trust. 
          As a result, the team naturally developed dashboards and alerting systems to monitor system performance. 
          I also introduced them to software teaming and mob programming, fostering greater collaboration and adaptability. 

      - layout: left
        title: Cazoo
        link: cazoo.co.uk

        sub_title: Senior Software Engineer
        caption: December 2019 - April 2023
        description: |
          At Cazoo we were following Extreme programming practices; TDD, pair programming, mob programming and continuous integration.        
          
          I initially worked with the team that was responsible for developing and maintaining the web application to allow customers to finance their cars.
          After a few months I've started mentoring other engineers to improve the quality of their systems.
          
          My main focus was to teach/mentor/coach other engineers in testing practices, quality, observability and pair programming techniques.
          I've introduced a few teams to hexagonal architecture and domain driven design.
          
          I've lead an initiative to improve and scale contract testing.
          
          Contract testing is a beauty and still a controversial topic. We were trying to reduce the amount of slow/brittle e2e tests via using Contract testing.
          Teams struggled to find common practices and to set up contract testing correctly. I've helped define and implement common tools to implement Contract testing.  
      
          What did I learn/improve?
          - Test driven development
          - Mob programming
          - Pair programming
          - Continuous delivery
          - Continuous integration
          - Hexagonal architecture
          - Trunk based development
          - Observability
          - Domain driven design
          - ... and more

      - layout: left
        title: Liberis
        link: liberis.co.uk

        sub_title: Senior Software Engineer
        caption: January 2019 - December 2019
        quote: >
          Short but sweet
        description: |
          At Liberis I had the opportunity to help the engineering team to define their frontend applications architecture.
          The team was originally using a functional framework called Elm. For hiring purposes Liberis decided to move to React.
          I've organised sessions and created templates to simplify the work to migrate to React. 
          
          What did I learn?
          
          Liberis was my second experience as a full stack engineer.
          The company was moving from on-premises services to the cloud! Wow. I didn't even know the meaning of on-premises! :)
          While helping with frontend technologies I dive into Kubernetes, docker and Azure cloud.           

      - layout: left
        title: MHR
        link: mhr.co.uk

        sub_title: Frontend engineer
        caption: May 2015 - June 2018
        quote: >
          Vittorio, welcome to the UK!! New adventures ahead.
        description: |
          I am originally from Italy. In 2015 I made a bold move, I've decide to move to the UK.
          I had a few years of self taught experience in programming, I had no idea what would be working in a bigger company where they use words like Agile, testing, deployments, etc.
          
          MHR was a though journey because I had no real commercial experience in programming. After a few months of struggle I step up and made a difference.
          I've stared exploring concept such as SOLID, Agile and test driven development. The company was not really doing these things but with a small working group we've managed to learn these independently and shared team with the company.                 
      

footer_show_references: true

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
